---
name: Documentation
on:
  pull_request:

  release:

  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
    build-docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.10'

            - name: Set up uv
              uses: astral-sh/setup-uv@v6
              with:
                version: "${{ env.UV_VERSION }}"
                enable-cache: true

            - name: Install dependencies
              run: |
                uv sync --locked --all-extras --dev

            - name: Build docs
              run: |
                uv run mkdocs build --strict

            - name: Tar doc files
              if: github.event_name == 'push'
              run: tar -cvf site.tar site

            - name: Upload doc artifact
              uses: actions/upload-pages-artifact@v3
              if: github.event_name == 'push'
              with:
                  path: ./site

            - name: Deploy to GitHub Pages
              if: github.event_name == 'push'
              uses: actions/deploy-pages@v4
              id: deployment
